pluginName = 1C:Workmate
providerName = 1C-Soft LLC

category.name = 1C:Workmate
view.name = 1C:Workmate

computer.name = Ask the 1C:Workmate
command.name.suggest = Suggest code
command.label.suggest = Suggest code
command.name.accept = Accept code
command.label.accept = Accept code
command.name.acceptpart = Accept part of code
command.label.acceptpart = Accept part of code
command.name.acceptline = Accept a line of code
command.label.acceptline = Accept a line of code
command.name.rollbackpart = Rollback part of code
command.label.rollbackpart = Rollback part of code
command.name.stop = Stop code completion
command.label.stop = Stop code completion
command.name.explain = Explain
command.label.explain = Explain
command.name.critic = Review
command.label.critic = Review
command.name.fixcode = Fix
command.label.fixcode = Fix
command.name.generatedoccomments = Generate doc comments for method
command.label.generatedoccomments = Generate doc comments for method
command.name.addcode = Add code
command.label.addcode = Add code
command.name.feedback = Feedback
command.label.feedback = Feedback
command.name.statusbar = 1C:Workmate info

menu.label = 1C:Workmate

page.name = 1C:Workmate
