<?xml version="1.0" encoding="UTF-8"?>
<project
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
  xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.e1c.edt.ai</groupId>
    <artifactId>bundles</artifactId>
    <version>1.0.3-SNAPSHOT</version>
  </parent>
  <artifactId>com.e1c.edt.ai.ui.common</artifactId>
  <version>1.0.3-SNAPSHOT</version>
  <packaging>eclipse-plugin</packaging>

  <build>
    <resources>
      <resource>
        <directory>.</directory>
        <includes>
          <include>plugin.properties</include>
          <include>restricted-types.properties</include>
          <include>prompts/**</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-compiler-plugin</artifactId>
        <configuration>
          <extraClasspathElements>
            <extraClasspathElement>
              <groupId>com.oracle</groupId>
              <artifactId>javafx</artifactId>
              <version>0.0.0</version>
              <systemPath>${java.home}/lib/javafx-swt.jar</systemPath>
              <scope>system</scope>
            </extraClasspathElement>
          </extraClasspathElements>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
