###############################################################################
# Copyright (c) 2023 1C-Soft LLC.
###############################################################################
# feature.properties
# contains externalized strings for feature.xml
# "%foo" in feature.xml corresponds to the key "foo" in this file
# java.io.Properties file (ISO 8859-1 with "\" escapes)
# This file should be translated.

# "featureName" property - name of the feature
featureName=AI SDK Feature

# "providerName" property - name of the company that provides the feature
providerName=1C-Soft LLC

# "description" property - description of the feature
description=AI

# "copyright" property - text of the "Feature Update Copyright"
copyright=\
Copyright (c) 2023 1C-Soft LLC.\n\n\
################ end of copyright property ####################################