echo copy the "javafx" directory from the .jar to "META-INF\versions" for the update
echo merging ...
jar --create --file javafx-swt.jar -m META-INF/MANIFEST.MF -C META-INF/versions/11 . --release 17 -C META-INF/versions/17 .
echo updating ...
move /y javafx-swt.jar ..\bundles\com.e1c.edt.ai.ui.common\libs