name = "pianikova-telegram-feed"
main = "worker.js"
compatibility_date = "2026-10-05"

[vars]
CHANNEL_USERNAME = "gattavasis"

[[d1_databases]]
binding = "DB"
database_name = "pianikova-telegram-feed"
database_id = "2e08b0f5-698d-487a-b1e1-4015174a3d1b"

# Add TELEGRAM_CHANNEL_ID and TELEGRAM_WEBHOOK_SECRET with `wrangler secret put`.
