<?xml version="1.0" encoding="UTF-8"?>
<!--
   Copyright (C) 2025 1C-Soft LLC
-->
<project
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
  xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.e1c.edt.ai</groupId>
    <artifactId>parent</artifactId>
    <version>1.0.3-SNAPSHOT</version>
  </parent>

  <artifactId>features</artifactId>
  <packaging>pom</packaging>

  <name>Features</name>

  <properties>
    <sonar.skip>true</sonar.skip>
  </properties>

  <modules>    
    <module>com.e1c.edt.ai.license</module>
    <module>com.e1c.edt.ai.feature</module>
    <module>com.e1c.edt.ai.common.feature</module>
    <module>com.e1c.edt.semantic.feature</module>
    <module>com.e1c.edt.ui.eclipse.feature</module>
  </modules>

</project>

