<?xml version="1.0" encoding="UTF-8"?>
<!--
   Copyright (C) 2025 1C-Soft LLC
-->
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.e1c.edt.ai</groupId>
    <artifactId>parent</artifactId>
    <version>1.0.6-SNAPSHOT</version>
  </parent>
  
  <artifactId>bundles</artifactId>
  <packaging>pom</packaging>
  <name>Bundles</name>
  
  <modules>   
    <module>com.e1c.edt.ai</module>
    <module>com.e1c.edt.ai.ui.common</module>
    <module>com.e1c.edt.ai.context</module>
    <module>com.e1c.edt.ai.ui</module>
    <module>com.e1c.edt.semantic</module>
    <module>com.e1c.edt.ui.eclipse</module>
  </modules>
  
  <build>
    <plugins>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-source-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <executions>
          <execution>
            <id>run-checkstyle</id>
            <phase>validate</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>

