bin.includes = build.properties,\
               feature.xml,\
               feature.properties,\
               license_ru.html,\
               license_en.html,\
               feature_ru.properties

root = root