providerName=\
1C-Soft LLC

featureName=\
1C:Workmate License Feature

# "licenseURL" property - URL of the "Feature License"
# do not translate value - just change to point to a locale-specific HTML page
licenseURL=license_en.html

copyright=\
Copyright \u00a9 2012-2025 1C-Soft LLC. All rights reserved.

# "description" property
description=\
1C:Workmate License Feature

# "license" property - text of the "Feature Update License"
# should be plain text version of license agreement pointed to be "licenseURL"
license=\
This License agreement governs the use of 1C:Workmate SOFTWARE PRODUCT \n\
by a party (from hereinafter, Licensee) that legally owns a copy of the software product \n\
obtained by accessing the official website of the copyright holder.\n\
\n\
Under this License agreement, the Licensee is granted a limited non-exclusive license for \n\
SOFTWARE PRODUCT usage.\n\
\n\
Exclusive rights for the above SOFTWARE PRODUCT that incorporates client and server computer \n\
software modules, integrated databases, standalone software updates and addons, and any \n\
accompanying materials in paper or electronic format, are owned by 1C-Soft LLC (as registered \n\
in Moscow, Russian Federation) and its licensers. By copying SOFTWARE PRODUCT to computer \n\
memory and submitting a website account request, the Licensee accepts the terms \n\
of this License agreement as effective and binding.\n\
\n\
This License agreement grants the Licensee a right to use SOFTWARE PRODUCT with restrictions \n\
as defined below. The Licensee must keep a copy of SOFTWARE PRODUCT and the text of this \n\
License agreement as confirmation of their rights to use SOFTWARE PRODUCT.\n\
\n\
Rights and restrictions\n\
\n\
\t  1. The Licensee can install and use SOFTWARE PRODUCT on computer, in accordance with \n\
\t     the accompanying documents. \n\
\n\
\t  2. Transfer of rights under this License Agreement to third parties is not allowed.\n\
\n\
\t  3. The Licensee agrees to refrain from violating the Copyright holder's exclusive rights \n\
\t     for SOFTWARE PRODUCT, such as, refrain (and prevent third parties) from the following \n\
\t     actions without explicit written consent of the Copyright holder:\n\
\n\
\t \t a. distribute SOFTWARE PRODUCT or its components, including distribution by granting \n\
\t \t    third parties access to SOFTWARE PRODUCT that was reproduced in any form, over network \n\
\t \t    or by other means;\n\
\n\
\t \t b. make any changes to SOFTWARE PRODUCT code;\n\
\n\
\t \t c. perform actions resulting in eliminated or reduced efficiency of copyright protection \n\
\t \t    tools implemented by the Copyright holder, including multiplexing software and hardware \n\
\t \t    or tools that modify software or hardware protection of SOFTWARE PRODUCT;\n\
\n\
\t \t d. use SOFTWARE PRODUCT with protection tools disabled or modified without the Copyright \n\
\t \t    holder's consent;\n\
\n\
\t \t e. reverse engineer the source code, decompile, and/or disassemble the SOFTWARE PRODUCT \n\
\t \t    software, except when it is explicitly permitted by applicable law, and only to the \n\
\t \t    extent it is explicitly permitted by applicable law.\n\
\n\
\t  4. The Licensee acknowledges that Internet connection may be required to use SOFTWARE PRODUCT \n\
\t     as intended, and agrees to bear any applicable expenses.\n\
\n\
\t  5. The Licensee agrees to use SOFTWARE PRODUCT at their own risk and "AS IS". The Copyright \n\
\t     holder makes no warranties or representations of any kind about fitness of SOFTWARE PRODUCT \n\
\t     for the Licensee's particular purposes, or about safety of the Licensee's data, and \n\
\t     cannot be held responsible for any damages the Licensee may incur due to loss of data \n\
\t     integrity or availability that resulted from usage of SOFTWARE PRODUCT. Moreover, \n\
\t     the Copyright holder bears no responsibility for any damage that may result from \n\
\t     installation and usage of third-party modules (plug-ins).\n\
\n\
\t  6. Third-party code usage notification.\n\
\t     SOFTWARE PRODUCT accesses particular functions of original third-party libraries and \n\
\t     components, including these distributed as a part of SOFTWARE PRODUCT package. \n\
\t     Third-party code notifications, as well as advice on obtaining the source code for \n\
\t     any particular third-party code, are available for the Licensee's information in \n\
\t     1C-EDT-NOTICES file that can be found in licenses folder of the distribution package.\n\

