pluginName = AI Eclipse: Enterprise Development Tools
providerName = 1C-Soft LLC

category.name = AI
view.name = 1C:Copilot

computer.name = Ask the AI
command.name.suggest = Suggest code
command.label.suggest = Suggest code
command.name.accept = Accept code
command.label.accept = Accept code
command.name.acceptpart = Accept part of code
command.label.acceptpart = Accept part of code
command.name.acceptline = Accept a line of code
command.label.acceptline = Accept a line of code
command.name.rollbackpart = Rollback part of code
command.label.rollbackpart = Rollback part of code
command.name.stop = Stop code completion
command.label.stop = Stop code completion
command.name.explain = Explain code
command.label.explain = Explain code
command.name.critic = Review code
command.label.critic = Review code
command.name.fixcode = Fix code
command.label.fixcode = Fix code
command.name.generatedoccomments = Generate doc comments for method
command.label.generatedoccomments = Generate doc comments for method
command.name.feedback = Feedback
command.label.feedback = Feedback
command.name.statusbar = AI info

menu.label = AI

page.name = 1C.AI Preferences
